### ISSUE TITLE
Installer not working?

### ISSUE THREAD

**Issue by samvdb** [TCNetSystems/OKP1Stationeers#1]
Cant seem to find any executables after installing the msi. Whats wrong?

**Comment by mloftis** [comment]
I actually just realized I'd screwed up the installer and not put in a shortcut.  I'm going to roll a new version here shortly, you'll have to uninstall the old version from add/remove programs first though.  Also sorted out getting the MSI/EXEs all signed.

**Comment by mloftis** [comment]
https://github.com/TCNetSystems/OKP1Stationeers/releases/tag/OKP1-Stationeers-Editor-v0.0.2
